spring.datasource.url=jdbc:postgresql://localhost:5433/hogwards
spring.datasource.username=student
spring.datasource.password= chocolatefrog


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

books.cover.dir.path=cover

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
logging.level.liquibase=ERROR
spring.liquibase.enabled=true

logging.level.root=info

server.port=8080
logging.level.org.springframework=ERROR
spring.profiles.active=dev